### ISSUE TITLE
Now Showing Slids not showing up. Unless I Refresh the page. 

### ISSUE THREAD

**Issue by TATUMTOT** [petersem/posterr#119]
I'm Currently running Version v1.14.2 Windows Binary.

Currently I have 3 browsers pointing to the Server.. in this example I have manually refreshed the Center Screen but the other wont show now showing unless I Refresh.

Not sure where to start the troubleshooting process. I also have discovered that if I start all three browsers fast or at the same time they all show the same poster. 

![image](https://user-images.githubusercontent.com/11933561/136264825-bfee7642-9d54-4278-a778-fa9e5c165efa.png)

**Comment by TATUMTOT** [comment]
{
    "password": REMOVED",
    "slideDuration": 20,
    "playThemes": "true",
    "genericThemes": "true",
    "fade": "true",
    "hideSettingsLinks": "true",
    "theaterRoomMode": "false",
    "plexIP": "REMOVED",
    "plexHTTPS": "false",
    "plexPort": REMOVED,
    "plexToken": "REMOVED",
    "onDemandLibraries": "Movies,TV Shows",
    "numberOnDemand": 75,
    "onDemandRefresh": 10,
    "sonarrCalDays": 3,
    "radarrURL": "REMOVED",
    "radarrToken": "REMOVED",
    "radarrCalDays": 30,
    "readarrCalDays": 60,
    "hasArt": "true",
    "shuffleSlides": "true",
    "custBrand": "broadwayregular",
    "titleColour": "#FAFAD2",
    "footColour": "#FAFAD2",
    "bgColour": "#000000",
    "enableNS": "true",
    "enableOD": "true",
    "enableSonarr": "false",
    "enableRadarr": "true",
    "enableReadarr": "false",
    "filterRemote": "true",
    "filterLocal": "true",
    "filterDevices": "",
    "filterUsers": "REMOVED",
    "customPictureTheme": "default",
    "serverID": "REMOVED",
    "sleepStart": "01:00",
    "sleepEnd": "06:00",
    "enableSleep": "true",
    "triviaTimer": "15",
    "triviaCategories": "18",
    "triviaNumber": "1",
    "triviaFrequency": "1",
    "pinNS": "true"
}

**Comment by petersem** [comment]
Great setup! First off, sorry that I haven't gotten back to you sooner on this. I've been taking a break on this for the last month. (free software does not pay the bills) ;) The Discord server will be more in my face if you have future issues. Please post your setup on the Discord channel, as I'm sure others would like to see it too. 

The default behaviour is to show now screening first, and then cycle through the slides before refreshing. In the settings, there is a 'pin now screening' option, which will force a refresh (and show) anything that is playing. It will then it will not move onto any other kinds of slides and all playing has completed. This works on a single display.

Now the problem, and why you are seeing the same slides. Posterr does not support multiple monitors. It creates a set collection of slides each refresh, which is what is displayed. This is why you are seeing the same thing. 

I did try to replicate the specific now screening issue you are having, however it went straight to now screening fine over 4 monitors, and phone, for me. These were all on chrome, so I'm not sure if it relates to whatever browser you are using? Can you tell me what is running behind the screens? (os, browser)

Regarding the same content showing, there is no reason why you cannot run three copies of posterr, on three different ports, in three different folders. When you call posterr.exe, just pass in the port number you want to use as a parameter, then browse to this from the screens you want to display it on. (eg. "posterr.exe 4321") If you vary the number of slides to show slightly, or even what displays on which monitor, this will greatly reduce the chance of seeing the same thing. 

Posterr on Windows, can also be setup as a Windows service using NSSM. This make life easier again.

**Comment by petersem** [comment]
Just another point, in a set size portrait screen configuration, it may look better without the background art being enabled. As it is now, sometimes this can look a little strange without seeing the rest of the background. Just a suggestion.

**Comment by TATUMTOT** [comment]
I will try to create 3 services and give that a go.

Thanks

**Comment by petersem** [comment]
Let me know how you go. It should be very simple.  
- create three folders, each with poster-win.exe in them
- run the three apps with different port parameters (you could put this is a batch file)
_(eg poster-win.exe 3001, poster-win.exe 3002, poster-win.exe 3003)_
- Point each monitor to a different port number
