### ISSUE TITLE
posterr periodically reaching out to logz.nesretep.net

### ISSUE THREAD

**Issue by SimonBrooker** [petersem/posterr#126]
Hi,

It is noted that posterr is periodically reaching out to logz.nesretep.net. I was unable to find any options within posterr for the disabling  of log reporting to developer or such. 

Can we get more information on what the purpose of this transaction is?
What information is contained within the data sent back?
Can it be stopped within the application or do I need to block with the firewall?

Thanks,
S

**Comment by petersem** [comment]
Hi, I've disclosed this somewhere here, but I can't find it. I'll put a mention up again.

The call to logz only occurs on application startup, and does two things:
- returns the latest version number of posterr which, if different, will show an upgrade notice on your settings page and in your posterr logs.
- it returns three bits of information to me. The unique posterr install ID (a guid), the version of poster you are running, and the core features enabled. (Eg now showing, on demand, trivia, etc) 

No IP numbers or sensitive information is returned to me. I use this information to roughly track the number of installs, and to see if features are being utilised or not. 

Here is an except from what I capture. As you can see, nothing is traceable back to the originator. You can block the call if you wish to, but if you do, you will not get version update alerts. Plus, it makes it impossible to know if people are actually using posterr or not. 

``` Thu Sep 02 2021 21:11:39 GMT+1000 (Australian Eastern Standard Time),uuid:1ceb5808-a5e7-46a6-8161-1d9f976442f2,version:1.15.0,nsEnabled:true,odEnabled:true,sEnabled:true,rEnabled:true,pEnabled:true,rdEnabled:true
Thu Sep 02 2021 21:12:38 GMT+1000 (Australian Eastern Standard Time),uuid:1ceb5808-a5e7-46a6-8161-1d9f976442f2,version:1.14.0,nsEnabled:true,odEnabled:true,sEnabled:true,rEnabled:true,pEnabled:false,rdEnabled:true
```
