### ISSUE TITLE
Allow choosing posters from combined library set

### ISSUE THREAD

**Issue by JakeWharton** [petersem/posterr#127]
I am only using the on-demand support to show existing content between two libraries. Currently I can somewhat achieve this by setting the refresh rate low and the poster count high, but it still biases the selection toward the library with fewer items.

Imagine I set refresh to 10m and display to 15s giving me 40 posters before refresh. If I set poster count from each library to 20 I get equal TV and movies despite potentially having 10x the movie count. If I set the poster count to the max, 75, then i get 150 posters and am subject to the randomization of the first 40 as to whether more movies or more TV are displayed. I could, in theory, get 40 TV posters straight!

I'm not quite sure how to accomplish what I'm after because I'm not sure how the implementation works. My best guess/suggestion would be a checkbox or toggle to change the behavior from choosing N posters from each library to choosing N posters from the combined library set.

Thus given say 1000 movies and 100 TV the items would first be combined into a 1100-item set from which 40 posters were chosen. This gives movies 10x the chance of being displayed over TV.

**Comment by petersem** [comment]
Yes, it currently gets n cards from each specified library, unless one library has less than, or close to n cards. It's not an exact science here, as I also have to avoid duplication. When it selects a random card, it checks to see if it already exists in the selected cards. If it does, it discards it and tries again. If it can't get a unique card after three tries, it stops pulling titles from that library and spits out a warning message in the logs. There is no bias in card selections from libraries. It will try to pull n cards from each library, providing it can get the unique titles.

I understand what you want, a fixed set of returned poster cards, regardless of libraries selected. Combining the dataset before choosing titles would do this, but many people prefer the equal distribution, regardless of library size.

I'll have a think about it, however I'm very mindful of keeping settings minimal and easy to understand.
