### ISSUE TITLE
Add "none" option to "Slide Transitions"

### ISSUE THREAD

**Issue by JakeWharton** [petersem/posterr#128]
From what I can tell, the animations are done in JS (via jQuery?) instead of CSS which means they run on the CPU. I run my client on a Raspberry Pi Zero which does not have the power to successfully complete the animations. What usually happens is that I'm left with a partially transparent image for 90% of the posters. Disabling the animation would allow underpowered clients to still successfully render every poster.

**Comment by JakeWharton** [comment]
I poked around a realized this is using a bootstrap carousel which means options here are extremely limited. So this is likely infeasible without rewriting to something else to power animation.

**Comment by petersem** [comment]
Hi, I'm planning on rewriting the whole transition FX part of posterr, so will see what I can come up with. Admittedly, I have only run this on a rpi 3 and 4, not a zero. I will see what I can come up with.

**Comment by petersem** [comment]
Less slides with a lower refresh rate, should improve performance too

**Comment by petersem** [comment]
closing issue as no further correspondence entered.
