### ISSUE TITLE
MagicMirror integration 

### ISSUE THREAD

**Issue by fillilutten** [petersem/posterr#129]
Would love to see a module for MagicMirror. It’s the perfect platform for this kind of project. Could this already be done? I guess running a iframe module is what you can do I’m the mean time?

**Comment by petersem** [comment]
It's on my list, but I just haven't looked at it yet. Yes an IFrame is an option, however I'm not sure if mm2 has issues with cross origin requests (cors), so I'm not sure if this works. I haven't tested it.

**Comment by petersem** [comment]
Thanks, I'll close this. Would be great to see your implementation in a shared image on discord.
