### ISSUE TITLE
Now Screening not working - Get full data: TypeError

### ISSUE THREAD

**Issue by jrcalvert** [petersem/posterr#135]
When something is playing in Plex, I get the following in the logs:
2/20/2022, 6:01:36 PM *Now Scrn. - Get full data: TypeError: Cannot read property 'toLowerCase' of undefined
✘✘ WARNING ✘✘ - Next Now Screening query will be delayed by 1 minute: (70 seconds)

I am running using your docker image.

**Comment by petersem** [comment]
This can happen if plex is not configured correctly in Posterr settings, or sometimes if there is no metadata for the specific movie/show you are watching.

is this happening for everything you play, or just a specific title?

**Comment by KingIzzymon** [comment]
@jrcalvert are you still having this issue?

**Comment by petersem** [comment]
closing as no response received, and working fine in my testing.
