### ISSUE TITLE
[Feature Request] Custom Urls

### ISSUE THREAD

**Issue by mckellip** [petersem/posterr#136]
Would be nice to have the option for custom urls that would be filter specific (e.g. Device, user, etc). That way I could have a tablet outside my theater room that would show that url or what is playing. Then I could have another tablet that would show the normal view of rotating through stuff.

I could install two instances but then any changes to settings would have to be updated on both.

**Comment by petersem** [comment]
There is no reason why you cant run multiple instances of posterr, both with different settings. You could set a second instance to only show now screening for your theatre room device, with other slide sources disabled. Posterr will scale from large to small screens.

Inside the theatre room, your posterr instance can have 'theatre mode' enabled. This will blank the screen when anything is playing. 

Hope that helps
