### ISSUE TITLE
Discord Server down - Embed question

### ISSUE THREAD

**Issue by Bboy486** [petersem/posterr#137]
Is there a way to allow embedding so I can embed this into Dakboard?

Enter a website URL, must be https. Note: some websites do not allow embedding which will result in a black background.

**Comment by petersem** [comment]
It should work, however it is really up to the page you want to embed it on. This is where cross-origin requests can be set. By default it is http for poster, however it also runs great behind a reverse proxy with a letsencrypt SSL certificate. 

Hope that helps
