### ISSUE TITLE
Sleep Timer not working

### ISSUE THREAD

**Issue by TATUMTOT** [petersem/posterr#151]
Any Ideas how to get the sleep timer to work. I thought I would give this a try again. 

Running Three instances for each dedicated monitor. 

App is running on a remote server and the webbrowser are pointed to the services on a remote machine.

**Comment by KingIzzymon** [comment]
The "sleep timer" just transitions to an all black screen.

What exactly is your expectation with the sleep timer function?

**Comment by TATUMTOT** [comment]
I think I got this all resolved. We'll it is working at least. I think it was using the time on the rendering PC vs server.

**Comment by KingIzzymon** [comment]
Oh good, I'm glad it's working for u now. Can we close this issue?
