### ISSUE TITLE
Ability to filter out specific libraries from Now Playing

### ISSUE THREAD

**Issue by ahughes03** [petersem/posterr#170]
I'd like the ability to filter out which libraries display for Now Playing. Ex: I have a music library that I frequently play at my work desk, but I'd prefer that library does not trigger Now Playing in Posterr. The ability exists for On Demand- I'm hoping it's possible to integrate for Now Playing.

**Comment by petersem** [comment]
One thing you could do is set the player devices to watch, excluding your work player. So unless you played this at home, it wouldnt show up.
