### ISSUE TITLE
Item title is randomly aligned

### ISSUE THREAD

**Issue by boultonn** [petersem/posterr#172]
The text below the artwork seems to align itself within the browser randomly.
Sometimes it's slightly off to the left or right, sometimes it is almost or completely off-screen.
Widening the browser sometimes reveals the text but sometimes it's so far off it's not possible. 
![Screenshot 2022-11-23 151929](https://user-images.githubusercontent.com/40239880/203583574-861de13f-3fa1-4e11-bc7d-92dad070fa6c.png)

**Comment by boultonn** [comment]
Seems to be limited to Firefox

**Comment by KingIzzymon** [comment]
Is this still a problem? I've just seen that when the text is too long, that it'll scroll from right to left. Working on Google Chrome.

Apparently Firefox has been a known problem. See [known issues.](https://github.com/petersem/posterr/wiki/Known-Issues)

**Comment by boultonn** [comment]
Yeah still occurs, but if it's a known issue then I'll close this.
