### ISSUE TITLE
[Feature Request] Import from Radarr/Sonarr based on select tags

### ISSUE THREAD

**Issue by KingIzzymon** [petersem/posterr#175]
Being able to choose only select tags from Radarr/Sonarr would allow us to control what pops up on our posterr. For example, I don't want my upcoming anime showing up on the Posterr in our theatre room. There is potential for harm

**Comment by petersem** [comment]
The easy fix for this is to run a second version of Posterr just for your media room. Posterr is very low resource impact, and justs needs a different port and config file save location.

**Comment by KingIzzymon** [comment]
> The easy fix for this is to run a second version of Posterr just for your media room. Posterr is very low resource impact, and justs needs a different port and config file save location. 

@petersem I think you might be misunderstanding me.

I want to see what's coming soon, but posterr shows ALL of what's coming soon based on Radar/Sonarr watch list.

So, just like you're currently able to filter content by genre from Plex, I'd like to filter content by tag from Sonarr/Radarr. It's possible via the API. Sonarr's "Import List" feature already does this so we might be able to adapt that bit of code for posterr.
