### ISSUE TITLE
[Feature Request] Add "Start time" and "End time" to the title banner

### ISSUE THREAD

**Issue by KingIzzymon** [petersem/posterr#176]
By repurposing some of the existing code for the progress bar, could we add "Start time" and "End time" to the title banner?

![image](https://user-images.githubusercontent.com/94716517/214357844-8a45d8bd-d9ab-4ef3-a114-a40f1015c40e.png)

**Comment by petersem** [comment]
Is start time actually useful? Is end time based on duration from start time, or time remaining?

Also, there is space in your mock up picture, but this is not how posterr looks. the title is customisable and often takes the entire width. There is not actually space on the header for this. I will have a think though.

**Comment by KingIzzymon** [comment]
End time is the actual time the video will end.

The image is from another software called (movieposterapp)[https://www.movieposterapp.com/]

The title banner can be held inside its own bounding box or iframe and the text can be set to dynamically change font size based on string length so that all characters stay visible within the box.

**Comment by KingIzzymon** [comment]
End time is the actual time the video will end.

The image is from another software called (movieposterapp)[https://www.movieposterapp.com/]

The title banner can be held inside its own bounding box or iframe and the text can be set to dynamically change font size based on string length so that all characters stay visible within the box.

**Comment by petersem** [comment]
I know that app. It didnt have the size flexability as Posterr has. It did look nicer, but a lot of this needed custom images to be used. I will think about some options though

**Comment by petersem** [comment]
@KingIzzymon  How is this? I can't put it at the top. 

![image](https://user-images.githubusercontent.com/1418289/219511485-68158bfc-9356-4d0a-9b48-d4713cbb34a4.png)

**Comment by petersem** [comment]
This is in the latest release now
