### ISSUE TITLE
Support for Sonarr V4

### ISSUE THREAD

**Issue by polklabs** [petersem/posterr#182]
Currently doesn't seem like Sonarr V4 is working. Only V3

**Comment by petersem** [comment]
Correct . v4 is part of the Sonarr development branch, of which they have not only changed the API path, but also the returned data. It is too much screwing around to add options for beta versions. Once v4 is released I will update poster. 

I have actually made the code adjustments ready for when v4 comes out, however most people are running sonarr v3.  Keep in mind that development branches can radically change from day to day. 

![image](https://user-images.githubusercontent.com/1418289/221722515-bd3d63a3-e284-4494-8356-53de2ad35a39.png)
