### ISSUE TITLE
Sonarr and Radarr 

### ISSUE THREAD

**Issue by tucker19** [petersem/posterr#187]
Seeing Sonarr and Radarr give back `*Coming Soon - TV: TypeError: raw.data.reduce is not a function`

**Comment by petersem** [comment]
Which versions are of sonarr and radarr are you using?

**Comment by mrttt2000** [comment]
I have the same issue but only for Radarr version 5.1.3.8246 I also went into the debug menu  and ran the Radarr test here is the result - 
** RADARR CHECK ** (Any releases in next 30 days)
-------------------------------------------------------
(node:1) UnhandledPromiseRejectionWarning: TypeError: resp.data.forEach is not a function
    at Health.RadarrCheck (/usr/src/app/classes/core/health.js:233:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)

**Comment by petersem** [comment]
Can someone please post the settings section for radarr? I cant replicate the problem.

**Comment by petersem** [comment]
Closing as I cannot replicate this, and no further feedback given
