### ISSUE TITLE
No Artwork will display

### ISSUE THREAD

**Issue by Vandekieft** [petersem/posterr#189]
Used docker and TrueNas Scale versions of the app. About 3 or so months ago the app stopped displaying any images/posters.  The connections work fine still though.

I did not find any issues with the configurations
I did not see anything being blocked in my network
The Application still generated the image links, but if you view them outside the app they are none existing images
I checked with Firefox, Brave, desktop and mobile just to make sure

**Comment by petersem** [comment]
Is it all images that are missing, or just for a specific thing? eg plex, sonarr, radarr, etc

**Comment by Vandekieft** [comment]
> Is it all images that are missing, or just for a specific thing? eg plex, sonarr, radarr, etc
> 

I had them all set up, and none of them were providing any images. I tried fresh docker container on a different system too, same thing.

I am going to troubleshoot some more tonight.

**Comment by JDShadowline** [comment]
I am seeing the same issue on my docker install. This is what was showing repeatedly in the logs:

```
RangeNotSatisfiableError: Range Not Satisfiable
    at createHttpError (/usr/src/node_modules/send/index.js:984:7)
    at SendStream.error (/usr/src/node_modules/send/index.js:270:31)
    at SendStream.send (/usr/src/node_modules/send/index.js:666:19)
    at onstat (/usr/src/node_modules/send/index.js:725:10)
    at FSReqCallback.oncomplete (fs.js:193:5)
```

**Comment by Vandekieft** [comment]
> I am seeing the same issue on my docker install. This is what was showing repeatedly in the logs:
> 
> ```
> RangeNotSatisfiableError: Range Not Satisfiable
>     at createHttpError (/usr/src/node_modules/send/index.js:984:7)
>     at SendStream.error (/usr/src/node_modules/send/index.js:270:31)
>     at SendStream.send (/usr/src/node_modules/send/index.js:666:19)
>     at onstat (/usr/src/node_modules/send/index.js:725:10)
>     at FSReqCallback.oncomplete (fs.js:193:5)
> ```
> 
> @Vandekieft , Are you using docker-compose? If so what does your docker-compose file look like for Posterr?

I have been too busy to check recently. But I did a compose via portainer, and just traditional CLI. My main method of using this app was through TrueNAS scale TrueCharts. I briefly did the docker builds and then removed them after they did not work. I figured it was something in my network at first so I then stuck witht he TrueCharts and was troubleshooting there. 

Eventually Ill get back to check it. Another busy week and I can't yet. Sorry for the lack of logs.

**Comment by Vandekieft** [comment]
So randomly this week some of the artwork started showing up again.  This was interesting because I did not change anything except for how my images are stored in Tautulli. I switched from Cloudinary to local.

I reviewed all the URLs that were for images in the postarr page and about 30% of them loaded real images and the remaining 70% still just displayed blank.  I still do not see any errors anywhere, but is Tautulli the main source for how the images are displayed? All my legacy urls for Tautulli still load the proper images.

**Comment by Vandekieft** [comment]
So randomly this week some of the artwork started showing up again.  This was interesting because I did not change anything except for how my images are stored in Tautulli. I switched from Cloudinary to local.

I reviewed all the URLs that were for images in the postarr page and about 30% of them loaded real images and the remaining 70% still just displayed blank.  I still do not see any errors anywhere, but is Tautulli the main source for how the images are displayed? All my legacy urls for Tautulli still load the proper images.

**Comment by petersem** [comment]
@Vandekieft can you share your compose yaml? Also, can you tell me how many on-demand titles you have selected? (less is more here. Better to keep it under 20, have 15-20 second slide transitions, and a 20 minute refresh period.

**Comment by Vandekieft** [comment]
So I started using Posterr with the TrueCharts build, but I figured that was the cause of my initial issue, so I just used the generic Compose template for testing and left it as it did not have any difference:

`version: '2.4'

services:
  posterr:
    image: petersem/posterr
    container_name: posterr
    environment:
      TZ: America/Denver
      BASEPATH: ""
    volumes:
      - /opt/posterr/config:/usr/src/app/config
      - /opt/posterr/custom:/usr/src/app/public/custom
    ports:
      - 9876:3000
    restart: unless-stopped`


I have had my on-demand at 15, 25, and 50. None of them made any difference.   I just have left posterr running even though I had this issue, and it comes and goes. A lot of the times it will be just the general blank view, and then randomly it will show the posters for most of the day. I really do not know where the issue lies. I know this is not very helpful but I was lost.  I was certain this issue was my network, but noting would confirm that. Then I was thinking TrueCharts, but still nope.  I run plenty of other docker containers with volumes in the same /opt/ matching similar or the same permissions but they all seem to work just fine.   

Here is what it mostly looks like...

![image](https://github.com/petersem/posterr/assets/834985/79c2e8eb-0235-4b91-ab76-fff9465a8aaf)

**Comment by NightHawkATL** [comment]
Looks like since the update to Radarr a few weeks ago, the images are not pulling correctly. I get the "poster not available" poster on all movies but the Sonarr TV posters still work. The latest update for Radarr requires enabling authentication and ever since that setting was enabled, I can't see the artwork/poster art. I have tried to disable the authentication but it is mandatory and I have tried to set it so that local access doesn't check SSL but there is no option to disable local authentication. 
![image](https://github.com/petersem/posterr/assets/8395658/208b2def-1fb1-4a38-a0d5-bfc8ab27de71)
![image](https://github.com/petersem/posterr/assets/8395658/7ede5d74-f209-4960-a787-eba12b6e76a7)

**Comment by OcifferAction** [comment]
> Looks like since the update to Radarr a few weeks ago, the images are not pulling correctly. I get the "poster not available" poster on all movies but the Sonarr TV posters still work. The latest update for Radarr requires enabling authentication and ever since that setting was enabled, I can't see the artwork/poster art. I have tried to disable the authentication but it is mandatory and I have tried to set it so that local access doesn't check SSL but there is no option to disable local authentication. ![image](https://user-images.githubusercontent.com/8395658/275610450-208b2def-1fb1-4a38-a0d5-bfc8ab27de71.png) ![image](https://user-images.githubusercontent.com/8395658/275611149-7ede5d74-f209-4960-a787-eba12b6e76a7.png)

I'm getting the same issue on my end. I've tried everything I can think of to remedy the issue, but nothing has worked.

**Comment by petersem** [comment]
Fixed in the lastest release (as of 5 minutes ago). Radarr changed the json data name for images (dont ask me why).
