### ISSUE TITLE
Executables for Linux, windows and Mac

### ISSUE THREAD

**Issue by petersem** [petersem/posterr#19]
Instead of just docker, create executables for the major 3 platforms.

**Comment by petersem** [comment]
using 'npm pkg' to try and do this. It does work to package all scripts and assets into binaries, however, the images and mp3's that are downloaded into cache directories, do not seem to be accessible in the web browser path. (obviously, the same thing works in docker or in dev.) I am just not quite sure how to work out this last part of the puzzle.

**Comment by mchangrh** [comment]
https://github.com/petersem/posterr/blob/fecf28e9a3057167561b70d863ff0fb49fdf22ed/classes/core/cache.js#L22

https://github.com/petersem/posterr/blob/fecf28e9a3057167561b70d863ff0fb49fdf22ed/classes/core/cache.js#L33

it should work if you replace the path with `process.cwd()` to get access to the local directory - `__dirname` and relative paths will probably not work

**Comment by petersem** [comment]
@mchangrh Hi Mate, thank wasn't the fix, but close. Essentially i had to continue as i was for fixed assets but use process.cwd() for the dynamically downloaded ones. 

Thanks heaps mate. Have it working now.  :)

  app.use(express.static(path.join(__dirname, "public")));  // css, javascript, etc
  app.use(express.static(path.join(process.cwd(), "saved"))); // downloaded images, etc

**Comment by petersem** [comment]
This will be included once out of beta, after v1.0

**Comment by petersem** [comment]
Still additional work to do, to make this all work, but the hard part is over. Watch this space :)

**Comment by petersem** [comment]
I've somehow broken this between having a broken Surface and having to rebuild my environment on a new machine. There won't be any updates to binaries until i get the time to focus on this. sorry! :(

**Comment by petersem** [comment]
the issue was the pkg npm needed to be updated, not my code. All is good again. Sample binaries distributed. Next release i hope to make these a regular part of the release cycle.

**Comment by petersem** [comment]
implemented
