### ISSUE TITLE
Sonarr v4 connectivity issues

### ISSUE THREAD

**Issue by IrishTR** [petersem/posterr#190]
Hello trying to get this working with Sonarr v4, one thing they added was require authentication to be enabled on Sonarr.  But it also allows for disabling when coming from a local address.  No matter though it doesn't appear to work.  Errors when attempting to make the connection.  Radarr and Readarr all behave fine just not Sonarr.  Sonarr is up and running accessible direct, via proxy and from other apps fine just not Posterr

posterr  | 6/23/2023, 4:00:31 PM *Sonarr - Get calendar data: Request failed with status code 404
posterr  | 6/23/2023, 4:00:31 PM *Sonarr - Get raw data: AxiosError: Request failed with status code 404
posterr  | 6/23/2023, 4:00:31 PM *Coming Soon - TV: AxiosError: Request failed with status code 404

Debug page when testing Sonarr results:
posterr  | 6/23/2023, 4:04:15 PM *SONARR CHECK - Get calendar data: Request failed with status code 404
posterr  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 26)

**Comment by petersem** [comment]
V3 is the latest stable release, so v4 is not yet supported. I have the code ready to go, but cant release it until is stable.

**Comment by Healzangels** [comment]
Recently having swapped over to the beta v4 build didn't think to check if would effect posterr. D'oh! Whoops.

Was wondering if you'd consider releasing a beta tag version or something similar for posterr that included the v4 changes. :) Love posterr so can't wait for sonarr to go stable and have coming soon again. Thanks!
