### ISSUE TITLE
[Feature Request] Show On-Demand posters from a playlist 

### ISSUE THREAD

**Issue by wklink** [petersem/posterr#192]
I create a playlist of movies that my kids have expressed interest in watching/re-watching.  Instead of (or in addition to) showing posters from an entire library, I'd like to make sure that the movies in a playlist of my choosing are shown.

**Comment by petersem** [comment]
Interesting idea. If you get a few upvotes for this, then I will look into it. Thatnks for the suggestion.

**Comment by petersem** [comment]
No community support for this, and is difficult as playlists are user, not server, centric. Closing.
