### ISSUE TITLE
Plex Connection On Demand + Now Screening no images.

### ISSUE THREAD

**Issue by Healzangels** [petersem/posterr#193]
Greetings!
Attempting to configure Plex to show On Demand items from my library. While I do see both features working as far as pulling both On Demand shows/Showing items that are currently being played I can't seem to get any art work to load. 

I have tested my configuration for Plex in a number of different fashions including https on https off, 443, 32400, hostname, ip address etc but none seem to allow the poster/art to load properly. There are no immediate errors in my logs after restarting however using the Debug feature On Demand test do see the following error: 

`PM *On-demand - title retrieval: Error: Plex Server didnt respond with a valid 2xx status code, response code: 404`

I am running this on an unRAID system in a Docker container. PMS is on the latest version and running the latest version 1.16.2 of posterr. 

Thanks!

**Comment by Healzangels** [comment]
D'oh well patience or lack there of (even though did see the change slide mentioned in FAQ) seems to be the trick. 
I've left posterr up in an open tab and slowly but surely I am starting to see art work populate. 

Apologizes for the unneeded pings/notifications! I am curious though is this something that will have a cache be created once I have setup and over time or is this based on the individual client browser. Thanks again for the awesome app!

**Comment by airbornetrooper82573** [comment]
What exactly did you do to get this to work?

**Comment by airbornetrooper82573** [comment]
Couple hours later and mine started working on its own.
