### ISSUE TITLE
Radarr images are not pulling correctly

### ISSUE THREAD

**Issue by OcifferAction** [petersem/posterr#200]
Looks like since the update to Radarr a few weeks ago, the images are not pulling correctly. I get the "poster not available" poster on all movies but the Sonarr TV posters still work. The latest update for Radarr requires enabling authentication and ever since that setting was enabled, I can't see the artwork/poster art. I have tried to disable the authentication but it is mandatory and I have tried to set it so that local access doesn't check SSL but there is no option to disable local authentication. 
![image](https://github.com/petersem/posterr/assets/8395658/208b2def-1fb1-4a38-a0d5-bfc8ab27de71)
![image](https://github.com/petersem/posterr/assets/8395658/7ede5d74-f209-4960-a787-eba12b6e76a7)

_Originally posted by @NightHawkATL in https://github.com/petersem/posterr/issues/189#issuecomment-1765011422_

**Comment by NightHawkATL** [comment]
Why was this opened up as a new issue with my post on a previous issue about the same?

**Comment by petersem** [comment]
Fixed in the lastest release (as of 5 minutes ago). Radarr changed the json data name for images (dont ask me why).
