### ISSUE TITLE
[Suggestion] Don't show the exact movie on multiple instances at the same time

### ISSUE THREAD

**Issue by simoneluconi** [petersem/posterr#201]
I would love to have multiple display showing some posters one next to each other, just like at the cinema, but sometimes they show the exact movie at the same time and it ruins a bit the illusion.

It would be nice if it was possibile to add an option for showing different movies between the instances of the web browser.

**Comment by petersem** [comment]
Easiest way to do this is to create a second container for posterr on a different port, then call this on the second monitor. The container uses very minor resources, so you could run a bunch of them if you wanted to.
