### ISSUE TITLE
Create an API for HA control

### ISSUE THREAD

**Issue by bystand3r** [petersem/posterr#202]
To have an api we can add in to HA to enable / control the sleep time.
So we could set quiz mode on 
Enable disabled now showing etc.

**Comment by petersem** [comment]
@bystand3r testing this at the moment. Stay tuned

**Comment by petersem** [comment]
API for screen blank toggle. 

curl commands:

> **Get sleep status: **
> `curl -X GET "https://posterr.nesretep.net/api/sleep" -H "Content-Type: application/json"`

> **Toggle sleep state: **
> `curl -X POST "http://your-posterr-url/api/sleep" -d '{"psw": "your-posterr-psw"}' -H "Content-Type: application/json"`

![image](https://github.com/user-attachments/assets/df967ce3-1944-403c-a3e5-e52009ced7e3)
