### ISSUE TITLE
Allow Pictures playlist to display

### ISSUE THREAD

**Issue by kevbodavidson** [petersem/posterr#204]
Pictures library in plex doesn't display for "on-demand". I want a slideshow of my favorite pictures to play when nothing is being watched, but now I have to make fake 10 second clips and update the poster of the clips to the picture slideshow I want to play

**Comment by petersem** [comment]
is this two seperate things? There is already a custom pictures function in settings to allow for all the custom pictures you want.

**Comment by kevbodavidson** [comment]
I put pictures in the custom folder, but It wouldn't work for me, but maybe it's a folder permissions issue. It would still be nice to have plex handle everything and just put Pictures in the on-demand blank and it pulls them from plex but super low priority since I have a work around and custom pictures does it as well.

**Comment by petersem** [comment]
The custom pictures feature is the way this is implemented. Make sure you put picures in the 'default' folder. Closing.
