### ISSUE TITLE
[Feature Request] Option to filter by library

### ISSUE THREAD

**Issue by polklabs** [petersem/posterr#205]
Example: I have TV, Movies and Music libraries but I only want to show TV and Movies on the now screening and ignore Music

**Comment by petersem** [comment]
Interesting idea. I will consider what is involved, then advise.

**Comment by petersem** [comment]
@polklabs sorry it's been a while, I haven't forgotten this request. One thing I thought of is that you can already filter by device. So if you play music on different devices to what you watch movies/shows on, then you can filter to only show for the TV's.

Could the be an option for you?

**Comment by petersem** [comment]
Development underway

**Comment by petersem** [comment]
Just about to push this change to production. Thanks for the suggestion.
![image](https://github.com/user-attachments/assets/7be5aee7-d9aa-4d20-941c-21b5decb593e)
