### ISSUE TITLE
Sort by Genre Before Scraping

### ISSUE THREAD

**Issue by aardvarkian** [petersem/posterr#206]
I have 1200 movies in one library called Films. I want to filter this down to just the best. I tried doing this by adding a Genre "Favorites" to posterr, And adding that to movies I want, but now only about 5 are popping up in the cycle.

I'm guessing what's happening is it's picking up 300 (the maximum) movies out of that library and *then* filtering those out by genre. Is it possible to genre sort first so that I can make sure more come through?

I considered using custom images instead, but couldn't get anything to come through that method. Mapped a share to /docker/posterr/custom/ and added them there but still nothing?

**Comment by petersem** [comment]
Custom pictures sit in the posterr/custom/pictures/default folder. Alternatively you can create any folder name under pictures, then select this from the settings page. 
![image](https://github.com/petersem/posterr/assets/1418289/b284478b-57ef-48c8-9345-a1a36d025b41)
****

Genres are a bit trickier. This is a limitation i found in the plex api where not everything is always returned. Until that is resolved, i cant do much.
