### ISSUE TITLE
posterr will not show now playing when access plex remotely

### ISSUE THREAD

**Issue by mzemaita** [petersem/posterr#207]
Plex app is hosted at my home, posterr server is hosted home on the same network on a virtual machine.

If I play from my account locally from my 192.168.x.x network posterr will display now playing movie.

If I access my plex server remotely posterr will not display now playing move.

Is this possible? if so what do I need to adjust? 

Thanks.

-MZ

**Comment by petersem** [comment]
Have you tried enabling the remote networks option? 
![image](https://github.com/petersem/posterr/assets/1418289/ebae61c3-53b7-4106-99d4-d0d40a597914)

**Comment by petersem** [comment]
closing as no response
