### ISSUE TITLE
On-Demand Refresh Period Validation Error Refers to Slide Duration Instead

### ISSUE THREAD

**Issue by ghammerton** [petersem/posterr#209]
When the On-demand Refresh Period is set to fewer than 10 minutes (eg 1 minute as shown below), the Validation error shown says, _"'Slide Duration' is required and must be 5 or more"_, but I expect this is meant to say, _"'On-demand Refresh Period' is required and must be 10 or more"_

<img width="1391" alt="Screenshot 2023-12-05 at 1 11 33 pm" src="https://github.com/petersem/posterr/assets/880910/5a2f61ef-ae45-4c35-9f77-8f76f058764f">

<img width="1391" alt="Screenshot 2023-12-05 at 1 11 41 pm" src="https://github.com/petersem/posterr/assets/880910/fef4d270-7834-4b3c-b5ff-22901001805e">

**Comment by petersem** [comment]
Thanks for spotting that, you are correct in your expectation. This is fixed, and will be pushed in the next release. (next few days)
![image](https://github.com/petersem/posterr/assets/1418289/40d4cc9c-f50c-4506-8809-d69fad677314)
