### ISSUE TITLE
Show title on "Now Screening" slide

### ISSUE THREAD

**Issue by andydrew23** [petersem/posterr#213]
Showing the title of what is currently playing would be a nice touch. I'm only seeing an option to hide user info. No option to show/hide the title of what is currently being played.

**Comment by petersem** [comment]
That is deliberately the case, as the poster will have the title of what is playing on it alreaedy.

**Comment by andydrew23** [comment]
I'll chalk this up to user error. The specific title that prompted me to post the issue was "Split" which was not matched to the correct title in Plex. The poster of the title pulled by Plex did not have the film name in the poster

**Comment by petersem** [comment]
> I'll chalk this up to user error. The specific title that prompted me to post the issue was "Split" which was not matched to the correct title in Plex. The poster of the title pulled by Plex did not have the film name in the poster

Yeah, posterr lives and dies by how good your library maintenance is. 🙂 A nice prompt to fix things in Plex  when you see them bad in posterr.
