### ISSUE TITLE
[Feature Request] Support for multiple Sonarr instances

### ISSUE THREAD

**Issue by benmwilson** [petersem/posterr#214]
Hello. With my current setup, I am running two instances of Sonarr. One dedicated to regular TV and another to anime/cartoons. I am wondering if there is planned support for displaying show information from two instances of Sonarr and/or Radarr.

**Comment by petersem** [comment]
Not at this stage. If enough people asked, then I could do it. To date, you are the only one.  But why two instances of sonarr? You can have multiple root folders, so you can send some titles to /tv and some to /anime-tv, for example.

**Comment by petersem** [comment]
Closed
