### ISSUE TITLE
No digital release date

### ISSUE THREAD

**Issue by Johnnybegood90** [petersem/posterr#218]
Add an option not to display upcoming content without a digital release date

**Comment by petersem** [comment]
Sometimes there is no digital release date, but there is a physical release date. The physical release generally corresponds to availability as well, so I check for both of these.

**Comment by Johnnybegood90** [comment]
Yes but, for one of my content, there's just a theater release date and it appear in comming sool

**Comment by petersem** [comment]
Which title? Let me know and I can investigate.

**Comment by petersem** [comment]
@Johnnybegood90 never-ending, I think I found an example. Looks like it is showing cinema releases too. I will investigate.

**Comment by Johnnybegood90** [comment]
Hi @petersem, sorry, GitHub didn't notify me of your message. Good thing you found one!

**Comment by petersem** [comment]
Should be fixed in latest release
