### ISSUE TITLE
Rotten tomatoes score

### ISSUE THREAD

**Issue by Johnnybegood90** [petersem/posterr#219]
Can you please add a rotten tomatoes score in the content info?

**Comment by petersem** [comment]
In the plex library settings you have selected the ratings agent, of which you can only select one. 'The movie database' had the most consistent populated ratings, so I went with that. Posterr gets most of its data from what is stored in Plex, so I can't add R.T ratings without losing the more consistently populate tmdb ratings.
![Screenshot_20240502_132458_Chrome~2](https://github.com/petersem/posterr/assets/1418289/0fd54722-1f6f-474b-975e-c9ccfda19514)
