### ISSUE TITLE
REQ: A couple of ideas for the future.....

### ISSUE THREAD

**Issue by quadcom** [petersem/posterr#222]
I got this up and running on a new pi5 and am already getting high WAF and kudos & compliments from friends.

I thought of a couple of ideas that I would like to see.

1. Theme support—It would be great if we could use our own CSS to move objects and change their appearance. We could then package these changes and share them here.
2. Premiere and Finale Label—Rather than just showing only premieres, it would be great if there was a little more emphasis on both premieres and finale episodes
3. Now Playing Counter—A timer under the playbar that could show how much time is left in the program.

That's all I got for now.

Thanks for putting this project out! I appreciate it!

**Comment by petersem** [comment]
I do like the idea of customisable themes, however I dont do this in Posterr. A big point of Posterr is that layout is automatic. You dont have to put in a million settings to make it work for different resolutions and orientations. To this end, css is locked down to accomplish this. 

Regarding the start, end, and remaining times, I did look at this, and it is _potentially_ possible. Why I didnt do this, is a lack of room on the title section. Whilst there may be room on your screen, this doesnt scale for smaller displays, where this text would be tiny. I will have a think about this though. Perhaps I could offer this as an optional setting?

Same deal for premieres and finales, in that real estate is limited. I will revisit this though, and see what fits.

All this is a little low on my list of priorites right now, so this could take a while before I investigate. (I'm currently looking to add movie trailers as an option) :)

**Comment by quadcom** [comment]
I suggested the custom CSS because of the details listed at the bottom. They are too small in relation to the poster image, especially for TV Shows displaying the season and episode numbers. Some things, IMO, are also not really important to see. For me, I don't really care if the show is on Netflix, Hulu, or HBO, nor the ratings for the show/movie. They just take up space. But that's just me, others may like all of that there. Options are a good thing but more work, that I know. 

As for the premiere/finale label, a relative-positioned div inside the .poster div containing the appropriate PNG or SVG (SVG would allow for customizing the colour) would do the trick. You could then offset that div to the top right corner, kind of like an 'On Sale' sign.

**Comment by petersem** [comment]
Yeah, good ideas, I like that. I will investigate implementing the options.

**Comment by petersem** [comment]
Under /custom/custom.css you can override the default look with your own css. Give it a try.
