### ISSUE TITLE
[Feature Request] Filter "Now Playing" libraries

### ISSUE THREAD

**Issue by c11umw** [petersem/posterr#231]
There's an option to select NOW PLAYING by User and Device, but there's no option to filter which Libraries to show.

Can this be added pls? Same as we have with the On-Demand libraries,

**Comment by petersem** [comment]
I'll look into it, but it may be a while due to other priorities

**Comment by c11umw** [comment]
I tried creating an account with restricted access (just Film+TV libraries), but it seems that we get the Plex token from the owner account only, which kinda makes sense 
Worth a try tho.

**Comment by petersem** [comment]
ok, now screen doesnt hook into libraries as such. It shows whatever is playing on the plex server. you can limit this by device, local/remote, or by user, which all reference the player device. It wouldnt make sense to limit by library as i dont have that info available. 

thanks for the suggestion, but in this case i cant implement it.

**Comment by petersem** [comment]
Actually, i take that back. Looks like I can do this, however I will do as exclusions. Essentially, you will be able to list the library names to exclude. For most people, this should be less work. I will close this request as it is being rolled into #205

**Comment by petersem** [comment]
The library exclude feature is about to go live.

**Comment by c11umw** [comment]
Nice 
Thanks for persisting with it :)
