### ISSUE TITLE
[Feature Request] Compatiblity with maloja

### ISSUE THREAD

**Issue by yoannfelix** [petersem/posterr#235]
[maloja](
https://github.com/krateng/maloja) is a self-hosted music scrobble database to create personal listening statistics. Together with the [multi-scrobble](https://github.com/FoxxMD/multi-scrobbler)r, you can gather statistics on all the sources where you are listening music, not only Plex but Spotify and Google music.

The API is [documented ](https://github.com/krateng/maloja/blob/master/API.md#api-documentation) and could display top charts on posterr

**Comment by petersem** [comment]
I like maloja, very cool. 
Posterr pulls metadata for show, movies, and music from Plex, it doesn't look up this metadata from other sources. The idea is that what you have in Plex, is what you see in Posterr. With this in mind, Posterr wouldn't be the right fit. If you could get this integrated with Plex, then Posterr could utilise this metadata.
