### ISSUE TITLE
[Feature Request] Include Recently Released Movies for On Demand

### ISSUE THREAD

**Issue by augustofellipe** [petersem/posterr#239]
I would like to suggest including a new Feature, to include **Recently Released Movies** for On Demand.

Thanks in advance.

I'm loving use Posterr, It's part of my family routine already. Appreciate the effort creating this tool.

**Comment by petersem** [comment]
Thanks for the suggestion. There is an option for recently added titles, which could be argued as being recently released for 'you'. Is this enough, or are you looking for titles that have recently become availailable?

**Comment by augustofellipe** [comment]
I'm looking for the titles that have recently become available.

![image](https://github.com/user-attachments/assets/31bc280f-d01a-4525-a812-2b97114e81bb)

**Comment by petersem** [comment]
Got it. For now, use recently added, which should still show recently released title, plus anything else added. 

I've put your request in the feature backlog, and will review to see if it gets any further requests.

**Comment by petersem** [comment]
@augustofellipe what do you consider recently released movies for on-demand? 

By the time they are downloaded to plex it could be months since it released at the cinema, at which point the recently added option would pick it up. So I'm not sure what the distinction would be.

**Comment by augustofellipe** [comment]
Hey Matt, thanks for taking a look at this. I believe it's the most recent movies available, despite the income downloads that will always be the first at the recently added movie library.


I'm looking for this library:
<img width="1034" alt="image" src="https://github.com/user-attachments/assets/bef0208e-59df-4992-b383-83e24a1d2105">

**Comment by petersem** [comment]
> Hey Matt, thanks for taking a look at this. I believe ...

Hi mate, Plex uses the 'originally available' tag for this. This is the cinema release date, which could be months before you get it in plex. If you look at the image I supply, you can see this example has an originally available tag about a moth before the digital tag. Where it gets trickier is that plex doesn't keep the digital date, and sometimes it doesn't have the originally available date. So the question remains as being 'what is recent?'. Is it originally available = now - 1 month or less If so, it will not have the media for anything delayed. If it's -2 months, then you are going to get a lot of older titles show as recent. 

I understand your reasons, but I don't think there is an easy way to consistently show by digital or physical release dates. I think the simplest is by added date. If you are using sonarr/radarr apps, then this should always include recently released, as they are added to plex when available.

Sorry I can't help you on this request further. 

![Screenshot_20240928_123931_nzb360](https://github.com/user-attachments/assets/ebe33a65-bfac-40a6-8b70-60a59ecc93e1)
