### ISSUE TITLE
Allow just the poster and no text in a full screen mode

### ISSUE THREAD

**Issue by jl94x4** [petersem/posterr#240]
I have a 7inch screen and have the 7inch screen in a picture frame, it would be good if we could have an option for full screen mode on just the poster, and no text above or below it!

Is this possible at all? :)

**Comment by petersem** [comment]
For on demand titles, you can hide the header and footer with two options in settings. Would this suffice?

**Comment by jl94x4** [comment]
I would prefer a global setting to remove them. I only use now playing and struggling to find a way to remove them.

**Comment by petersem** [comment]
Edit a file at ./posterr/custom/custom.css and put in the following css. This will hide the header and footer for all slides. I don't support changes you make here, but you have full control to.update the layout.
![Screenshot_20241001_225346_Admin Hands](https://github.com/user-attachments/assets/cfb8fd43-6aa2-48b4-b73f-27102254339f)
![Screenshot_20241001_225236_Chrome](https://github.com/user-attachments/assets/7f8dba2e-0faf-4a22-aaa6-6ba9d8d4cc91)
