### ISSUE TITLE
Nothing displayed

### ISSUE THREAD

**Issue by Saruchan92** [petersem/posterr#242]
I can't get anything to display, just stays at the black screen with the settings link. I have it installed via Docker Compose, and other containers do have connection to my Plex server, so I'm thinking it's nothing to do with Docker or the container's networking. The only thing I can think is it's my Plex connection settings in there. 

Here are my current settings:
password: suppressed
slideDuration: 60
playThemes: true
genericThemes: true
fade: true
hideSettingsLinks: false
theaterRoomMode: false
plexIP: 192.168.4.5
plexHTTPS: false
plexPort: 32400
plexToken: suppressed (what's displayed per Plex link instructions, token after "X-Plex-Token=")
numberOnDemand: 4
onDemandRefresh: 30
sonarrCalDays: 3
radarrCalDays: 30
readarrCalDays: 60
hasArt: true
custBrand: emerald_greyregular
recentlyAddedDays: 4
titleColour: #FAFAD2
footColour: #FAFAD2
bgColour: #000000
enableNS: true
enableOD: false
enableSonarr: false
enableRadarr: false
enableReadarr: false
filterRemote: true
filterLocal: true
filterDevices: suppressed
filterUsers: suppressed
enableCustomPictureThemes: true
customPictureTheme: default
serverID: f3e68c6e-fa07-4288-ad50-3795021469e3
sleepStart: 00:00
sleepEnd: 07:00
triviaTimer: 15
triviaCategories: 27,9,20,28,16,26,15,11,12,14,18,22,23,19,24,17
enableTrivia: true
triviaFrequency: 300
pinNS: true
hideUser: true
enableLinks: false
enableCustomPictures: false
enableSleep: false
enableAwtrix: false
rotate: false

It appears that getting XML from the Plex for Windows app and going by IP on a browser to my server results in the same token, but going through app.plex.tv to my server is a different token. I tried both, and currently have the token directly from my server entered. I've tried playing movies through all three things listed above, and nothing's happened yet. Tried "On Demand" as well, still nothing. 

It's been more than a day since the container started, so I'm doubting that it's things still loading. Anything I've done wrong?

**Comment by petersem** [comment]
@Saruchan92 have you tried the on-demand test in settings-debug? The results should display in the container logs 
![Screenshot_20241010_160425_FullScreenBrowser](https://github.com/user-attachments/assets/e20f373e-dc25-4fd0-8f94-cc2ba85b096b)
for posterr.

**Comment by petersem** [comment]
@Saruchan92 what else is displayed in the posterr container logs?

**Comment by Saruchan92** [comment]
@petersem for both "Now Screening" and "On-Demand" checks I'm getting "Error: socket hang up". Ping tests are all true.

**Comment by petersem** [comment]
Can you join me in the discord support chat, at https://discord.gg/TZT48aZK

a little easier than comments here. Once we resolve things, I can update back here.

**Comment by petersem** [comment]
set plex to 'preferred' under settings - network' 
![image](https://github.com/user-attachments/assets/5d21e6f5-8cae-47e5-bf9a-6c75d6f7bfef)
