### ISSUE TITLE
 Plex Server denied request

### ISSUE THREAD

**Issue by Bboy486** [petersem/posterr#244]
I am not sure what this is asking me to do. I have had this working for a year and just recently saw this issue. 

10/14/2024, 8:00:09 PM *Now Scrn. - Get sessions: Error: Plex Server denied request, you must provide a way to authenticate! Read more about plex-api authenticators on https://www.npmjs.com/package/plex-api#authenticators
10/14/2024, 8:00:09 PM *Now Scrn. - Get raw data: Error: Plex Server denied request, you must provide a way to authenticate! Read more about plex-api authenticators on https://www.npmjs.com/package/plex-api#authenticators
10/14/2024, 8:00:09 PM *Now Scrn. - Get full data: Error: Plex Server denied request, you must provide a way to authenticate! Read more about plex-api authenticators on https://www.npmjs.com/package/plex-api#authenticators
✘✘ WARNING ✘✘ - Next Now Screening query will be delayed by 1 minute: (70 seconds)
10/14/2024, 8:00:49 PM *Radarr - Get calendar data: Request failed with status code 401
10/14/2024, 8:00:49 PM *Radarr - Get Raw Data: Error: Request failed with status code 401
10/14/2024, 8:00:49 PM *Coming Soon - Movies: Error: Request failed with status code 401
✘✘ WARNING ✘✘ - Next Radarr query will run in 1 minute.

**Comment by petersem** [comment]
@Bboy486 Looks like your plex-x-token may have changed. This can happen when migrating to a new server, unclaiming/reclaiming the server, or logging the server out and in for the main plex user address. Either way, check your plex-x-token and try again.

Let me know

**Comment by petersem** [comment]
Closing due to no response. Pls re-open if issue requires remains.
