### ISSUE TITLE
Add fonts to Posters

### ISSUE THREAD

**Issue by MrPatate87** [petersem/posterr#246]
It will be great to let user to add fonts to Posterr.
Hope this idea can be integrated easily.

**Comment by petersem** [comment]
I'd like this, but i cant implement this. Web safe fonts have to be hard coded in css. They also have to be tested that they will fit default text at different resolutions.

If there is a specific font or two that you want then raise a issue with font name, and I'll see what I can do.

**Comment by MrPatate87** [comment]
The face I really like to use is Neutraface, if you could add it it will make me so happy !!
