### ISSUE TITLE
Title on Now Screening

### ISSUE THREAD

**Issue by MrPatate87** [petersem/posterr#247]
Actually  in the Posterr settings I have understand the Now Screening Alternate Text can only be a fixed text.
Can it be possible to show the Movie or tv show title insteed of a fixed text??

Hope it can be possible.

**Comment by petersem** [comment]
It has to refect the type of slide, not the title of the slide. This distinguishes if it's coming soon, on-demand, now screening. 

It would be confusing to make this the title of the show or movie. You may be able to do this with the custom.css option, but any changes you make are not supported by me.
