### ISSUE TITLE
Plex Not connecting

### ISSUE THREAD

**Issue by Goku532** [petersem/posterr#250]
I have tried to connect posterr to plex and it does not connect. I gave it the token and ip address of my local server and it does not connect. Is there any kind of a guide to get it working with plex.

**Comment by petersem** [comment]
Did you enter 32500 for port?

Also, try turning off the secure option if you set thus.

**Comment by Goku532** [comment]
I have the 32400 port in there and I have the https turned off

**Comment by Goku532** [comment]
![Screenshot 2024-12-23 000047](https://github.com/user-attachments/assets/1c4bbf7d-0149-47ac-9c96-e8c365b7c3f9)
I tried with and without the http:// and I removed my ip address from the screen shot

**Comment by petersem** [comment]
Just the ip goes in. Is your plex server set to prefer secure or always secure? Set to prefer

**Comment by petersem** [comment]
There is also z discord server if that's easier.

https://discord.gg/S6QxSwy5

**Comment by petersem** [comment]
Here's mine
![Uploading Screenshot_20241223_174148_FullScreenBrowser.jpg…]()

**Comment by Goku532** [comment]
Mine is set to preferred and I could not see your screen shot. It seems like it was not uploaded.

**Comment by petersem** [comment]
@Goku532  what shows in the posterr container logs?

![Screenshot_20241223_174148_FullScreenBrowser](https://github.com/user-attachments/assets/5348548a-4ccd-450b-a3bf-88ba3159eb51)

**Comment by petersem** [comment]
- Start playing some plex media
- in posterr settings there is a debug section. Go there and run the now showing test
![Screenshot_20241224_003348_FullScreenBrowser](https://github.com/user-attachments/assets/55f835bb-00b6-46e8-a698-8564c3d247b6)
- go to the logs for the posterr container and see what the test results say.
![Screenshot_20241224_003458_Chrome](https://github.com/user-attachments/assets/ec6aad93-0eca-4816-bcfc-687c0c844eea)

**Comment by Goku532** [comment]
Where would I find the logs after hitting the Now Playing Test?

**Comment by Goku532** [comment]
Ok that is working which I didn't know how it did. Does it display posters from movies you have in your collection or just what is playing?

**Comment by petersem** [comment]
> Where would I find the logs after hitting the Now Playing Test?

This is the container. You can do the command `docker logs posterr` or if you have portainer installed, you can view logs there.

**Comment by petersem** [comment]
> Ok that is working which I didn't know how it did. Does it display posters from movies you have in your collection or just what is playing?

Yes, that's the on-demand section. I'm glad that's working now. I'll close this issue. Further general questions are probably easier to ask in discord. 

Enjoy.
