### ISSUE TITLE
Do not show R rated titles 

### ISSUE THREAD

**Issue by petersem** [petersem/posterr#33]
Suppress on-demand titles NR or R

**Comment by Darkwolf1515** [comment]
As in an option for it? or just a flat ban.

**Comment by petersem** [comment]
@Darkwolf1515 An option. Some of the R-rated movie posters are pretty scary if you have little kids.

**Comment by petersem** [comment]
> As in an option for it? or just a flat ban.

an option to hide

**Comment by petersem** [comment]
Exclusion of content ratings is now available for on-demand
