### ISSUE TITLE
On-demand titles drawn from recently added

### ISSUE THREAD

**Issue by petersem** [petersem/posterr#39]
Add an option to make on-demand titles come from recently added lists

**Comment by TATUMTOT** [comment]
Yes this would be nice.

**Comment by zinjacoder** [comment]
A bit of a variant to consider wrt Plex... 

[PlexMetaManager](https://github.com/meisnate12/Plex-Meta-Manager) creates collections based on various online lists.  trakkt, imdb, best-of-2021, etc... 

From what I can see it adds a "Label" to each movie or show that contains the name of the target collection.  If it were possible to query these "Labels", we could have the benefit of having the On-demand group display our Trending, Popular, Favorites,... etc

![2022-04-16 21_46_33-Plex](https://user-images.githubusercontent.com/727898/163696871-0674a649-52ea-46ae-9f57-f4be6eabaf9a.jpg)

Thanks for your work!!  Much appreciated!

**Comment by petersem** [comment]
Recently added has been Implemented in v1.15.3
