### ISSUE TITLE
remove on-demand text

### ISSUE THREAD

**Issue by binarygeek119** [petersem/posterr#50]
i like to be able to remove the word on-demand for showing over poster

**Comment by petersem** [comment]
I've consider the option to allow text changes here. You could then just remove the text.

**Comment by Berserkir-Wolf** [comment]
Would changing the "on-demand" headers to a badge (like the media details below) also achieve a similar result (aesthetically)?

**Comment by petersem** [comment]
i think the 'pill' format would be too small, considering what that this is not a media player

**Comment by petersem** [comment]
Feature to customise all banner text has been released in v1.3.0. A future release will address hiding on-demand titles and footers

**Comment by petersem** [comment]
Until there is a formal option to hide the on-demand banners, you can still do this by putting in a custom on-demand banner with just a space.

**Comment by petersem** [comment]
Now in current release
