### ISSUE TITLE
add logo to top

### ISSUE THREAD

**Issue by binarygeek119** [petersem/posterr#51]
i would like to add a logo to the top.
like my cinema name 
on other software(which is dead now) i had a png of a logo i made that would be displayed on top of poster

**Comment by petersem** [comment]
Early prototypes had this, along with images for studios, 4k, etc. I ended up dropping this as these were difficult to scale and keep quality for. 

I leave this open, but it's low on the list for now.

**Comment by petersem** [comment]
The other option I considered, with custom images

**Comment by petersem** [comment]
This is too difficult to do when you there is a priority to auto-scale the screen. I won't be implementing this. Sorry.
