### ISSUE TITLE
showtimes

### ISSUE THREAD

**Issue by binarygeek119** [petersem/posterr#55]
i would love to be able to have show times listed
i can see this a few ways

1. have the times show under the artwork when poster is showing
2. switch to a list of times after X posters, that move down a list slowly and once it reaches the bottom of the list it switches back to the poster view
3. have a way have setting movies to have showing times like big showing at 10:30 and 3:40
4. and have a way to randomly set showtimes i think it need to take into account movie length 
5.

**Comment by petersem** [comment]
You can already create your own channels in the DVR and live tv section of plex with DizqueTV. It's possible to pull in the guide xml for a dizquetv guide or xteve feed for Posterr, but im wondering if this is getting more into the Plex space and less for Poster?

**Comment by binarygeek119** [comment]
What I was meaning by that is as if it was a real cinema and was show movies at X times they wouldn't have any real meaning just give the   Allusion of a real cinema

**Comment by petersem** [comment]
So just an image? Or a fake guide?

**Comment by Darkwolf1515** [comment]
Yknow how when you walk into a theater it shows all the showtimes? what he wants is for the posters to show at the bottom or top "showtime: 1:30-2:45" or whatever

**Comment by petersem** [comment]
> Yknow how when you walk into a theater it shows all the showtimes? what he wants is for the posters to show at the bottom or top "showtime: 1:30-2:45" or whatever, with it cycling through the movies that will play next.

But where is this schedule coming from? I get the idea, but unless it's real data, i don't see how this would add value. Plex is all on-demand, unless you are talking DVR and EPG.

**Comment by petersem** [comment]
Im not sure this makes sense to keep open. I will provide a custom image slide in the near future, which could be used for this. If there is a way to schedule playing media for plex in the future, then we can revisit it.
