### ISSUE TITLE
multiple displays

### ISSUE THREAD

**Issue by binarygeek119** [petersem/posterr#56]
i am running two displays from old pc monitors running FullPageOS

[](https://github.com/guysoft/FullPageOS)

and it works great but it will show two of the same poster at the same time

i like a way to prevent this

**Comment by petersem** [comment]
Just run up a second copy of Posterr, with different docker folders (/docker/poster1..PosterrN) and ports, the run the other one in the other screen. It uses negligible resources and is designed to allow multiple copies to run

**Comment by petersem** [comment]
Hope this solves the issue
