### ISSUE TITLE
Allow custom images

### ISSUE THREAD

**Issue by binarygeek119** [petersem/posterr#57]
i would love to load up some custom poster for ads

my idea is like a poster that would have popcorn on it and say dont forget to hit the concession stand for some popcorn

or show a big glass of coke/pepsi

have a custom cinema logo poster (my home cinema)

and have to display every X posters

if you like i could make some ad posters to bundle with this app

**Comment by binarygeek119** [comment]
just a quick sample

![SAMPLE](https://user-images.githubusercontent.com/72405030/119217206-3e6f1b00-ba9e-11eb-985f-dbf67862c831.jpg)

**Comment by petersem** [comment]
This is actually something I started to code, but de-prioritised. It's a great idea and I'll add in post v1

**Comment by petersem** [comment]
@binarygeek119 Would this just be a poster only, with no header or footer?

**Comment by binarygeek119** [comment]
I think just add custom poster like the current just pull from custom source

**Comment by petersem** [comment]
in progress

**Comment by petersem** [comment]
Implemente in v1.7.0
