### ISSUE TITLE
not accessible from host IP, only from localhost

### ISSUE THREAD

**Issue by mchangrh** [petersem/posterr#58]
In the docs, it references accessing `http://hostip:9876`. However, it seems that the process is not accessible or the docker-proxy is only routing to localhost

**Comment by petersem** [comment]
The 'hostip' is the actual IP number of the machine that is running docker. Is that what you are using?

**Comment by mchangrh** [comment]
no firewalls, no iptables rules aside from docker.

tried through public IPv4, IPv6, DNS and wireguard. I can try to replicate on another machine

**Comment by mchangrh** [comment]
Seems to be issue with only one machine, Will raise a ticket with support there.

Thanks for the quick response!
