### ISSUE TITLE
Error when running posterr

### ISSUE THREAD

**Issue by jeffreyswiggins** [petersem/posterr#64]
Started receiving this error that is causing POSTERR to not run

posterr       | -------------------------------------------------------
posterr       |  POSTERR - Your media display
posterr       |  Developed by Matt Petersen - Brisbane Australia
posterr       |
posterr       |  Version: 0.9.2
posterr       |
posterr       |  BBBB   EEEEE  TTTTT    A      !!
posterr       |  B   B  E        T     A A     !!
posterr       |  BBBB   EEEEE    T    A   A    !!
posterr       |  B   B  E        T   AAAAAAA
posterr       |  BBBB   EEEEE    T  A       A  !!
posterr       | -------------------------------------------------------
posterr       | ✅ MP3 cache cleared
posterr       | ✅ Web server started on internal port 3000
posterr       | ✅ Image cache cleared
posterr       | ✅ Settings loaded
posterr       |
posterr       | --- Enabled Status ---
posterr       |    Plex: true
posterr       |    On-demand: true
posterr       |    Sonarr: true
posterr       |    Radarr: true
posterr       |
posterr       | 5/27/2021, 5:57:28 PM Coming soon 'tv' titles refreshed
posterr       | 5/27/2021, 5:57:28 PM Coming soon 'movie' titles refreshed
posterr       | 5/27/2021, 5:57:28 PM On-demand titles refreshed (Movies,TV Shows)
posterr       |
posterr       | ✅ Application ready on http://hostIP:3000
posterr       |    Goto http://hostIP:3000/settings to get to setup page.
posterr       |
posterr       | /usr/src/app/classes/core/cache.js:66
posterr       |         var size = parseInt(res.headers["content-length"], 10);
posterr       |                                 ^
posterr       |
posterr       | TypeError: Cannot read property 'headers' of undefined
posterr       |     at Request._callback (/usr/src/app/classes/core/cache.js:66:33)
posterr       |     at self.callback (/usr/src/node_modules/request/request.js:185:22)
posterr       |     at Request.emit (events.js:327:22)
posterr       |     at Request.onRequestError (/usr/src/node_modules/request/request.js:877:8)
posterr       |     at ClientRequest.emit (events.js:315:20)
posterr       |     at Socket.socketErrorListener (_http_client.js:426:9)
posterr       |     at Socket.emit (events.js:315:20)
posterr       |     at emitErrorNT (internal/streams/destroy.js:92:8)
posterr       |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
posterr       |     at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by petersem** [comment]
was this from a missing folder?

**Comment by jeffreyswiggins** [comment]
Something on my end... after the 2nd reboot of my docker server everything smoothed out.  Not sure what happened.  I blame the weather and gremlins

**Comment by petersem** [comment]
all good

**Comment by jeffreyswiggins** [comment]
and I STILLL SO DIG THIS APP
