### ISSUE TITLE
Feature Request: Jellyfin support

### ISSUE THREAD

**Issue by Darkwolf1515** [petersem/posterr#68]
Would be great to see alongside Plex, as i've been hoping for something like this!

**Comment by Darkwolf1515** [comment]
God I searched jellyfin and nothing came up, grrr, closed.

**Comment by petersem** [comment]
leave it open.. i just havent looked at yet. because jf is open source, i can go through the actual app and try to intuit the api. will just be time consuming

**Comment by petersem** [comment]
but in hindsight, this is a copy of a previous enhancement #49, so closing this one.
