### ISSUE TITLE
Black screen on ipad

### ISSUE THREAD

**Issue by Rickexe** [petersem/posterr#73]
Hello, 

I really like posterr. I wanted to use it on my iPad 2 and put it on the wall outside of my theater room. Unfortunately when I go to the page my posterr instance is on it gives me a black screen. On pc and phone it works. But not on iPad. 

What is the problem?

**Comment by petersem** [comment]
I'm not sure. What browser are you using? Tried it with chrome?

I don't have an iPad and have not tested with Safari browser.

**Comment by Rickexe** [comment]
I tried safari, chrome and also a kiosk browser app. It's an iPad 2 on ios 9.3.5 so it's pretty old. I have had issues before with other things where the iPad couldn't load the javascript because it's just obsolete. 

I tried a firefox docker image on my server to access it on the iPad through that. But for some reason I couldn't reach the ip address on the iPad.

I think I have to come up with some workaround. Any suggestions?

**Comment by petersem** [comment]
yeah, an ipad 2 is definitely uncharted territory. the javascript in posterr really needs something built in the last decade and a half :)

only thing i could suggest is if you can jailbreak it and somehow load a newer browser on it. You could try edge too, if it will load. Somehow, i think the version of chrome (and other browsers) that are supported on the ipad 2, may be just too old.

Definitely not in the supported bucket though. May be easier to just run off something else

**Comment by Rickexe** [comment]
I tried edge. The same. I have jailbroken it but unsure what to do. I'm pretty sure the alternative browsers on ios are just safari with skins. So it makes sense that none of them work. 

This is the only tablet I have and I don't really want to buy a cheap android tablet just for this purpose. Posterr is a PERFECT way of reusing an old tablet like this one. 

That would make it easier if you could borrow one yeah.

**Comment by petersem** [comment]
I did try on a borrowed iPad2, but the javascript engines on the iPad2 supported browsers just seem to be too old. I'd venture to say that a lot of web functionality wouldnt work on an ipad 2 anymore.

**Comment by Rickexe** [comment]
Aaah that's too bad. I've been trying to make use of the my iPad 2 for the last 2 years. I never gave up on it until now. It's just a piece of junk. Thanks for helping me anyway!! 

I suppose I'll think of it as a collectors item then xD. 

Maybe someday I'll get a tablet and finally have an awesome Posterr display outside of my theater room. 

This issue can now be closed.

**Comment by petersem** [comment]
Thanks mate. Sorry about that. The iPad 2 is just too old. If i come up with anything, I will reach out.
