### ISSUE TITLE
issues and suggestions

### ISSUE THREAD

**Issue by ReenigneArcher** [petersem/posterr#96]
I just discovered this and have to say it's pretty cool. Thank you for providing this to the Plex community! Also I have a couple of issues to report and some suggestions as well.

**Issues:**
1. The position of the title text is not consistent. I would normally expect this to be centered, but sometimes it is all the way to the left, sometimes, it is almost completely off the screen to right, sometimes it is somewhere in between, and sometimes it is not visible at all.
2. The playback of theme music is sporadic. I had this running for about two hours before it started playing theme music, which was seemingly triggered by me resizing the browser window (not repeatable). As soon as I refresh the page the theme music stops though and doesn't seem to start again for a while, not sure what causes it to start when it decides to.

**Suggestions:**
1. Add a checkbox to "don't show again" when saving the settings. Or alternatively an option you can select under "general settings" to disable this popup.
![image](https://user-images.githubusercontent.com/42013603/129826536-b05f5194-156f-4bf9-aabc-4985ff2c5f17.png)
2. For Now Screening, have an option to only include certain libraries, or use the same values as the On Demand section.
3. Show a font preview in the settings page so the user doesn't need to save and reload the main page to see what the font would look like.
4. Add an option to exclude specific genres in On Demand section. The app just showed me a Christmas movie, so would probably be good to exclude stuff like that as it doesn't make sense to show year round.
5. Fade in and out of theme music when transitioning to next item.

**Comment by petersem** [comment]
Thanks for that. 

- What browser are you using? (Firefox is not supported) 
- How many on-demand titles are you showing? 
- how many on-demand libraries have you listed?
- What version are your running?
- Are you running the binaries or as a docker container?

ill address the enhancement requests in a different response.

**Comment by petersem** [comment]
Re enhancements:

- I'm making the saved popup into just an alert that will show, then fade away. (Annoys me too) 🤣
- now screen will always show what is screening. You can limit this by device, user, or local/remote plays
- font preview is already there in latest version
- fade in/out is something I've thought about. Will raise an enhancement request. It will be a tricky one though

**Comment by ReenigneArcher** [comment]
> 
> 
> Thanks for that.
> 
>     * What browser are you using? (Firefox is not supported)
> 
>     * How many on-demand titles are you showing?
> 
>     * how many on-demand libraries have you listed?
> 
>     * What version are your running?
> 
>     * Are you running the binaries or as a docker container?
> 
> 
> ill address the enhancement requests in a different response.

I am using Firefox. I saw it was not supported after I submitted my issue. Do you plan to add support for Firefox?

10 titles, 2 libraries for on-demand.

Version 1.110

Binary for Windows 10

**Comment by ReenigneArcher** [comment]
> 
> 
> Re enhancements:
> 
>     * I'm making the saved popup into just an alert that will show, then fade away. (Annoys me too, as is) 🤣
> 
>     * now screening will always show what is screening. You can limit this by device, user, or local/remote plays. I won't be putting limits on libraries or genres unless there is overwhelming requests for it.
> 
>     * font preview is already there in the latest version
> 
>     * music fade in/out is something I've thought about. Will raise an enhancement request. It will be a tricky one though

Cool, can't wait for the enhancements and hopefully you'll add library limits. Without the limits I probably won't use the now-screening feature.

Thanks!

**Comment by petersem** [comment]
> > Thanks for that.
> > ```
> > * What browser are you using? (Firefox is not supported)
> > 
> > * How many on-demand titles are you showing?
> > 
> > * how many on-demand libraries have you listed?
> > 
> > * What version are your running?
> > 
> > * Are you running the binaries or as a docker container?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ill address the enhancement requests in a different response.
> 
> I am using Firefox. I saw it was not supported after I submitted my issue. Do you plan to add support for Firefox?
> 
> 10 titles, 2 libraries for on-demand.
> 
> Version 1.110
> 
> Binary for Windows 10

Firefox is a hard browser to work with. For instance, the music issue is happening because Firefox is stopping the auto-play of media. This can be resolved be turning off blocks somewhere in the Firefox settings. It also adheres to different standards than a lot of other browsers, hence layout issues. So in these cases, there would be significant rewrites required to make it work. This would then have a flow-on effect where I'd possibly break things in other browsers. Things like auto-play of themes, or JavaScript downloads of media in the background are something I can't fix with code in every case. 

Sorry, but the answer is no. I'm not planning on adding Firefox support. Please use a different browser for Posterr.

I think all the issues you are having are probably attributed to Firefox. Can you see if they are resolved by using Chrome, Edge, or most other browsers. (That said, I don't have a Mac, so Safarri is unlike to work too)

**Comment by ReenigneArcher** [comment]
It seems to be better in Chrome, besides having to go full screen for themes to activate.

**Comment by petersem** [comment]
> It seems to be better in Chrome, besides having to go full screen for themes to activate.

Any window resize will trigger a browser refresh. The reason themes dont start immediately is becuase they havent had a chance to load yet (they come from the internet, not your plex server). You can mitigate this by having at least a 10-12 second slide delay. 

Ultimately, this is still a web-based app. So lots of slides, art, themes, posters, etc, with rapid transitions will cause initial delays

I'll take this issue being resolved now. if not, please re-open it.

**Comment by petersem** [comment]
btw, the fade-in/fade-out should actually be easy. Im just testing it now. I will also look to see if i can implement some additional caching for music.
