### ISSUE TITLE
old Docker version

### ISSUE THREAD

**Issue by Famku** [petersem/posterr#97]
Hi,

Posterr on Docker is still on 1.10.2

Can you please check

btw great software

cheers

**Comment by petersem** [comment]
Have you done a manual pull or are you running watchtower? current release is 1.11.something.

**Comment by Famku** [comment]
You are right, I pulled the old one.
Now it works.
Thanks

**Comment by petersem** [comment]
> You are right, I pulled the old one.
> Now it works.
> Thanks

i'll be releasing 1.12.0 in the next few days too. So keep an eye out for it, if you haven't automated updated.
